nodeLinker: node-modules

packageExtensions:
  "*":
    peerDependencies:
      vite: "*"
    peerDependenciesMeta:
      vite:
        optional: true

supportedArchitectures:
  os:
    - linux
  cpu:
    - x64
    - arm64
